### ISSUE TITLE
Azure Host V7 Host DisplayName

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.Host.AzureCloudService#49] opened 2016-05-20 13:55 UTC
The endpoint name no longer shows the Role Instance Id as was intended. [This line](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L131) does not set the DisplayName property which is used by ServicePulse and other items to provide a user-friendly way to identify the Cloud Service instance.

To change the DisplayName in NServiceBus V5 the setting must be set by accessing the settings direclty:

`configuration.GetSettings().Set("NServiceBus.HostInformation.DisplayName", "displayName");`

NServiceBus V6 includes a configuration option to configure this directly:

```
configuration
    .UniquelyIdentifyRunningInstance()
    .UsingNames(instance, host)
    .UsingCustomDisplayName("displayName");
```

In addition for NServiceBus.Host.AzureCloudService the initialization can be simplified by removing the lines ([127](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L127), [130](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L130)) relating to setting the host id since line [131](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L131) performs the same function:

```
                var host = SafeRoleEnvironment.CurrentRoleName;
                var instance = SafeRoleEnvironment.CurrentRoleInstanceId;
                configuration
                    .UniquelyIdentifyRunningInstance()
                    .UsingNames(instance, host);
```
### Plan of Attack
- [x] Host V6 (for NServiceBus V5) ~~PR~~ open a separate issue #54 
- [x] Host V7 (for NServiceBus V6) PR #53
- [ ] Doco PR

Connects to https://github.com/Particular/NServiceBus.Azure/issues/310

**Comment by boblangley** [comment] 2016-05-25 14:21
@Particular/azure-host-maintainers Is this something that should be back-ported to 6.0?

**Comment by boblangley** [comment] 2016-05-25 15:58
My apologies, I see now it is in the POA.

**Comment by SeanFeldman** [comment] 2016-05-25 15:59
@boblangley I'm a maintainer and have *no idea* where this PoA is coming from...

**Comment by SeanFeldman** [comment] 2016-05-25 16:05
@MarcinHoppe we cannot mix both v6 and v7 in the same issue. If decision is to backport the fix to v6 and release a hotfix, v7 information become irrelevant for the release notes. I'll open a new issue for v6.

**Comment by SeanFeldman** [comment] 2016-05-25 16:30
@boblangley could you please a separate issue for azure host v6 as a bug with milestone 6.2.5? Thank you.

**Comment by boblangley** [comment] 2016-05-25 16:34
@SeanFeldman will do.

**Comment by MarcinHoppe** [comment] 2016-05-25 19:13
@SeanFeldman I'm sorry I jumped the gun and filled the PoA without consulting the maintainers. My idea was to have two PRs, each attached to a respective milestone to play nice with release notes automation. Having two issues is of course as good.

**Comment by SeanFeldman** [comment] 2016-05-25 19:43
No worries @MarcinHoppe. We might not need an issue for host v7 release notes if the issue is addressed in host v6 as a hotfix.

**Comment by MarcinHoppe** [comment] 2016-05-25 20:44
Hotfix should be enough.

**Comment by SeanFeldman** [comment] 2016-05-25 21:50
## Analysis

### Core

* `DisplayName` is set to be the `RuntimeEnvironment.MachineName` by default.
* `HostId` is a unique calculated identifier of where the endpoint is running. Core by default sets it to deterministic GUID of `fullPathToStartingExe` and `RuntimeEnvironment.MachineName`.

### SC

SC is "re-mapping" the data from core to its own info

* SC.`HostId` <= Core.`HostId`
* SC.`Host` <= Core.`DisplayName`
* SC.`HostDisplayName` <= Core.`DisplayName`

### SP

In azure host v6, SP is showing each endpoint instance as `endpoint@DisplayName`, BUT endpoints are stored and managed in SC by using `HostId` which is consistent and unique, regardless of what `DisplayName` is. I.e. when azure machines are re-provisioned, `DisplayName` is changing, but SC does not add a new endpoint records.

In Azure host v6, an endpoint instance would be represented as `endpoint@machinename`. Each time an instance would be re-provisioned, the machine name would change to a random value providing no value. 

**Recommendation**: set custom display name (`.UsingCustomDisplayName(customDisplayName)`) to the combination or the role instance name _and_ role instance id, so that SP shows each instance as `endpoint@workerrole_0`. This representation will remain consistent throughout any changes in the physical machine names of the endpoint instances.

@Particular/servicecontrol-maintainers and @yvesgoeleven could you please review this and provide feedback?

**Comment by johnsimons** [comment] 2016-05-25 21:57
@SeanFeldman your comment above, should it say "In azure host v7" ?

**Comment by johnsimons** [comment] 2016-05-25 21:58
@SeanFeldman That is exactly what customers want, so :+1:

**Comment by johnsimons** [comment] 2016-05-25 21:59
Can we please patch previous versions to also do this ?

**Comment by johnsimons** [comment] 2016-05-25 22:00
Does this work for both AzureServiceBus and AzureStorageQueues ?

**Comment by SeanFeldman** [comment] 2016-05-25 22:03
@johnsimons there's an issue for azure host v6 as well :) hotfix will be going out.
In regards tot he transport (ASB/ASQ) - shouldn't affect at all.

**Comment by WojcikMike** [comment] 2016-09-30 08:31
@boblangley can you let me know where we stan with this? I simply wonder what we need to do to close this: 
https://github.com/Particular/ServicePulse/issues/309

**Comment by SeanFeldman** [comment] 2017-07-04 19:01
Closed by accident?

**Comment by danielmarbach** [comment] 2017-09-12 07:56
@boblangley is there anything left to do here? It seems this item is really outdated but the PoA shows that only doco would be left.

**Comment by boblangley** [comment] 2017-09-13 18:33
@danielmarbach Correct.

Doco was not updated, although @yvesgoeleven added a small section that is semi-related: https://docs.particular.net/nservicebus/hosting/cloud-services-host/faq#host-identifier

I opened a [doco issue](https://github.com/Particular/docs.particular.net/issues/3217) with some pulled together notes. I don't think I will get to it today to try to take a stab at this.

**Comment by SeanFeldman** [comment] 2018-08-22 14:56
Doco issue is still opened, but the change to the host was implemented.
Given that documentation issue is tracked, closing this one as completed.

**Closed by SeanFeldman** 2018-08-22 14:56 UTC
