### ISSUE TITLE
Removing an item from the blobstorage sometimes causes the host not to execute

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.Host.AzureCloudService#19] opened 2015-12-18 10:46 UTC
When removing an item (although sometimes it happens with updating as well) the host is unable to read the files anymore, causing it to stall. Fix is to download another one, re-upload it so it kicks off, but it would be great if the host could provide this out of the box, without requiring manual action.

It doesn't always happen so I'm thinking it might have something to do with, for example, reading the files while the changes are still being flushed to disk or something like that.

My Shared host configuration is as follows:

```
<Setting name="DynamicHostControllerConfig.ConnectionString" value="DefaultEndpointsProtocol=https;AccountName=***;AccountKey=***;" />
<Setting name="DynamicHostControllerConfig.AutoUpdate" value="true" />
<Setting name="DynamicHostControllerConfig.UpdateInterval" value="60000" />
<Setting name="DynamicHostControllerConfig.Container" value="endpoints" />
```

Below is the (somewhat cryptic) log, where you can see it error's, stops and then starts again once I upload an endpoint that is still in the blob storage again:

```
2015-12-18 07:19:16.266 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-18 07:19:16.297 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-18 07:19:16.328 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-18 09:45:53.054 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-18 09:45:53.117 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-18 09:45:53.148 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-18 09:45:55.969 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner Could not read C:\Resources\directory\66889e942e03494e8bc90d9e23c4f69a.Host.Shared.endpoints\***.zip as a zip file
2015-12-18 09:45:55.969 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner The system cannot find the file specified
2015-12-18 09:45:55.969 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner The system cannot find the file specified
2015-12-18 10:06:58.663 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-18 10:38:49.852 INFO  DefaultFactory Logging to 'E:\approot' with level Info
```

Another one, similar behavior:

```
2015-12-17 11:32:38.107 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 11:32:38.204 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 11:32:38.246 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 12:07:50.902 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 12:08:53.144 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 12:08:53.175 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 12:29:00.512 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 12:30:02.541 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 12:30:02.575 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 19:12:06.202 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 19:21:06.986 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 19:29:07.470 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 19:29:10.560 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner Could not read C:\Resources\directory\66889e942e03494e8bc90d9e23c4f69a.Host.Shared.endpoints\***.zip as a zip file
2015-12-17 19:29:10.560 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner Cannot start process because a file name has not been provided.
2015-12-17 19:29:10.560 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner Cannot start process because a file name has not been provided.
2015-12-17 19:36:11.299 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2015-12-17 19:36:57.820 INFO  DefaultFactory Logging to 'E:\approot' with level Info
```

**Comment by yvesgoeleven** [comment] 2015-12-18 11:44
Thanks for reporting, we'll look into this

**Comment by janpieterz** [comment] 2016-01-26 08:05
Had it happen another time today (I was updating 4 endpoints after each other, automatically):
```
2016-01-26 06:48:15.359 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2016-01-26 06:48:15.390 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2016-01-26 06:48:15.421 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2016-01-26 07:02:36.669 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2016-01-26 07:52:15.015 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2016-01-26 07:52:15.594 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2016-01-26 07:52:16.047 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2016-01-26 07:52:16.077 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner 
2016-01-26 07:52:17.560 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner Could not read C:\Resources\directory\66889e942e03494e8bc90d9e23c4f69a.Host.Shared.endpoints\Intreba.Arke.Endpoints.Archiver.zip as a zip file
2016-01-26 07:52:17.560 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner The system cannot find the file specified
2016-01-26 07:52:17.560 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner The system cannot find the file specified
2016-01-26 07:52:17.560 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner The system cannot find the file specified
2016-01-26 07:52:17.560 ERROR NServiceBus.Hosting.Azure.DynamicEndpointRunner The system cannot find the file specified
````

**Comment by janpieterz** [comment] 2016-01-29 07:44
Happened more or less once every single day in the last three days. I deployed around 11 times during these times. Possibly interesting flow of deployment is that it picks up every endpoint, ZIPs it and deploys it, so they don't all get dropped at once.

**Comment by janpieterz** [comment] 2016-02-03 05:30
@yvesgoeleven any ideas or progress with this? 

Wouldn't mind trying to fix it myself, it happens quite regularly, on production as well as on staging and therefore our automatic deployment story is quite unreliable.

**Comment by janpieterz** [comment] 2016-02-03 07:24
Browsing through the code a bit, I noticed two things: 
The DynamicEndpointRunner logger is used in classes that are not the DynamicEndpointRunner. Not sure if this is by design or not but this was a bit confusing to figure out, I was wondering why the heck that location would throw this error until by accident I saw the logger in the DynamicEndpointProvisioner actually referencing the DynamicEndpointRunner.
The error gets throw by the following lines, where it almost seems like the new Zipfile requests permissions that it can't have yet. I'm not a 100% sure why. [This answer](http://stackoverflow.com/a/4139847/1202118) on StackOverflow hints at the file actually being shared as read, which might then cause the ZipFile to error?

``` c#
using (var fs = new FileStream(localFileName, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.Read))
{
    blob.DownloadToStream(fs);
}

using(var zip = new ZipFile(localFileName))
{
    zip.ExtractAll(localDirectory, ExtractExistingFileAction.OverwriteSilently);
}
```

I've been looking around how this process gets started but it looks like it all starts in the DynamicHostMonitor, which checks for updates every Thread.Sleep(interval). It gets all zip files, fetches their attributes and then adds zips to either an added, updated or removed list and executes these event handlers. In my case it's basically the OnUpdatedEndpoints which gets called every time. The event handlers are all synchronous so it's not possible that somehow a double event can occur, causing the zip file to be somehow corrupted. The Provisioner downloads and extracts the files, which is where the error occurs. I tried to test if Storage possibly allows partial uploads to be visible already, but even when running 20 parallel uploads and a listblobs call every 100ms it only returned the 'blobs' when they were already present and totally uploaded.

**Comment by yvesgoeleven** [comment] 2016-02-05 07:42
If you log on to the machine where the zip file is downloaded, can you open it there?

**Comment by janpieterz** [comment] 2016-02-08 11:13
I've just tested it and indeed I cannot open it. Error is below. Downloading ZIP manually didAlso noted that it basically always throws a couple of errors when deployed (the couple of lines without any description in them) but it seems to be able to recover from that.

What I did notice is that on every deployment (of 4 endpoint) it creates 4 lines with an error in the dynamic endpoint runner (or one if it's log-sharers). This happens every time, but only sometimes it results in the zip file being corrupted. 

![image](https://cloud.githubusercontent.com/assets/383634/12882878/c40af23e-ce54-11e5-8311-7cd5cf0fd972.png)

**Comment by yvesgoeleven** [comment] 2016-02-08 15:17
Sounds like the zip gets corrupted somehow, if it can be opened from storage, but not from disk, then something goes wrong during transfer. Wonder how we can test/validate this?

**Comment by janpieterz** [comment] 2016-02-08 16:10
Next time it occurs I'll try and make 100% sure the zip on the storage is actually ok. If the problem could be downloading the zip, it could also be the uploading of course.

Just to make sure my assumption is correct, there's no way another part of the Shared Host is accessing the zip files, somehow multi-threading the extraction somehow or anything like that?

**Comment by janpieterz** [comment] 2016-02-08 16:22
To specify further: I'm uploading 4 individual blobs from different machines (two) to the same container, so they'll drop in at slightly different times, sometimes they don't all get picked up in the same 60 second interval. I have tested the table storage and partially uploaded blobs aren't shown until they're complete.

**Comment by yvesgoeleven** [comment] 2016-02-09 09:58
As far as I know, there is no parallelisation going on, only 1 thread is responsible for downloading the files

**Comment by janpieterz** [comment] 2016-02-12 14:29
I can confirm I just had it happen with zip files that, when downloaded from the endpoints folder manually, were fine to extract.

It sadly happened on production so couldn't dive any further (as in see if having the same code as used here for downloading it would produce the same result).

**Comment by janpieterz** [comment] 2017-01-11 15:25
Any progress/thoughts about this? 
We're still encountering it (product is still on NSB v5).

**Comment by SeanFeldman** [comment] 2017-01-12 23:49
It looks like the issue is with the [`DynamicEndpointLoader`](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/5851d99c4fd9be0be737f39027764ec68cc1a64a/src/NServiceBus.Hosting.Azure/DynamicHost/DynamicEndpointLoader.cs#L27) that is supposed to return all the zip files, but doesn't actually check if the found zip files are valid zip files. 

By evaluating those files and returning only those that can be read/used, this should solve the issue.

**Comment by janpieterz** [comment] 2017-01-13 07:08
That seems to make sense (if that detection is solid of course).

Would that still enable the re-download (for whatever reason)? The 'source' zip in the blob storage is solid, it's just the download that gets corrupted.

Would it help if I could offer up an invalid zip? If I encounter it again I'll try and go in and extract one (sadly we just had a burst of deployments, might take a while).

**Comment by SeanFeldman** [comment] 2017-01-13 12:19
> Would that still enable the re-download (for whatever reason)? The 'source' zip in the blob storage is solid, it's just the download that gets corrupted.

No, that would not 😞 But it will prevent from failures. You'd need to monitor logs for errors.

> Would it help if I could offer up an invalid zip?

Yes. I wonder if it's also some sort of edge case.

**Comment by janpieterz** [comment] 2017-01-13 12:22
In that case, the failures currently are basically the endpoint being shut down and not starting with the new one (nor the old one). What would the difference in failure mode then be? 

Will send a zip when encountering it!

**Comment by janpieterz** [comment] 2017-01-24 07:36
Just had another outage of 6 hours, monitoring didn't scream as loud as we expected it to, but at the core because of this. 

Given that the outage was this long and undetected I didn't have the opportunity to retrieve the zip file. 
It was also in the middle of the night.

**Comment by SeanFeldman** [comment] 2017-03-02 15:02
@janpieterz could you please email this to sean(dot)feldman(at)particular(dot)net?

**Comment by janpieterz** [comment] 2017-03-02 15:11
Email sent, thanks.

**Comment by janpieterz** [comment] 2017-04-09 07:22
@SeanFeldman just wanted to let you know that as part of the move to V6 we've moved away from using the AzureCloudService (in order to get reliable deployments). 

For us this isn't relevant anymore for now.

**Comment by SeanFeldman** [comment] 2017-04-09 09:56
@janpieterz we're still going to tackle it 😃 
What did you decide to use as your host?

**Comment by janpieterz** [comment] 2017-04-10 06:16
I chose the 'default' host (https://github.com/Particular/NServiceBus.Host). For now it does what it needs to and I manage the deployment via Octopus directly (with the cloud service we anyway had a 'nasty' way to deploy those endpoints).

**Comment by danielmarbach** [comment] 2017-06-29 15:31
There are not options for us when the zip container is corrupted. We are not able to reproduce this problem. Nowadays with WebJobs, ServiceFabric and more there is a variety of hosting options available that supersede the cloud service host. Since there is a workaround to move to NServiceBus.Host we are closing this.

**Closed by danielmarbach** 2017-06-29 15:31 UTC
Labels: State: Backlog, Type: Bug
